version: '3.8'
services:
   db:
      image: mysql:8.0.40-debian
      container_name: property-db
      ports:
         - "3308:3306"
      environment:
         MYSQL_ROOT_PASSWORD: 123456
         MYSQL_DATABASE: property