spring:
  application:
    name: Property
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
         format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/property
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8000
  servlet:
    context-path: /
project:
   singer-key: 0zyrZ7gaZCP/bIFTKMLLyuJXj8od3xeE4FDbsFGi1soFZNqvYCNQdb7lAUEVo=Ni41Qw8LEVLIHRHJIuvebQeUFjCx3SFNMtyXqLovUp1srRvDMC4NzAJuUHt4Uu=4hoCAEqg7IV=/pGEq=Sywo4!f5GG8XgQeZ4at330LC41E!6hlBTBJ!-hYI7SXjb!RQlCr88mfqR3wVw-0zwbYWGESIs7CU72y!w9kAKxTiVQQU5F9fujgoahnI3IkM-uG1n
   